version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - dev.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - dev.env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: