# Generated by Django 5.0.4 on 2024-05-02 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_alter_businesscard_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactrequest",
            name="requestor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_contact_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
