# Generated by Django 5.0.4 on 2024-05-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_contactrequest_contact_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="form_step",
            field=models.IntegerField(default=1),
        ),
    ]
