# Generated by Django 5.0.4 on 2024-05-02 13:40

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesscard",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="businesscard",
            name="user_photo",
            field=models.ImageField(
                upload_to="images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="businesscard",
            name="vcard",
            field=models.FileField(upload_to="vcard_files/"),
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="PL"
                    ),
                ),
                ("name_and_surname", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=320, null=True)),
                (
                    "company_or_contact_place",
                    models.CharField(max_length=150, null=True),
                ),
                ("contact_date", models.DateField(null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
