# Generated by Django 5.0.4 on 2024-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_contactrequest_requestor"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="contact_topic",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
